name: Build macOS
on: 
  push:
    branches:
      - figbug/build_mac

jobs:
  build:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Run script"
        run: ./ci/mac/build
        shell: bash
        env:
          APPLICATION: ${{ secrets.APPLICATION }}
          INSTALLER: ${{ secrets.INSTALLER }}
          APPLE_PASS: ${{ secrets.APPLE_PASS }}
          APPLE_USER: ${{ secrets.APPLE_USER }}
